const KEY='master-linked-state-v1';
const defaultTemplate=`{GivenName}，您好啊！\n\n我是华为加拿大研究所的 Daniel Jiang。我们近期正在提前了解 NeurIPS 2026 的参会情况，希望更好地参与会议并与相关领域的研究人员保持联系。\n\n因此冒昧请问一下：您今年是否计划参加 NeurIPS 2026？如果参加，预计会去哪个会场？\n\n感谢您的时间，祝好！\n\nDaniel`;
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{contacts:[],template:defaultTemplate};
state.contacts=(state.contacts||[]).map(c=>({...c,status:c.status||'pending',notes:c.notes||'',sentAt:c.sentAt||''}));
let selected=new Set();
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function given(name){return (name||'').trim().split(/\s+/)[0].replace(/[（(].*$/,'')}
function render(){const q=($('#search').value||'').toLowerCase(), f=$('#statusFilter').value; const rows=state.contacts.filter(c=>(f==='all'||c.status===f)&&[c.name,c.company,c.status,c.notes].join(' ').toLowerCase().includes(q)); $('#stats').textContent=`${state.contacts.length} 位联系人 · ${state.contacts.filter(c=>c.status==='sent').length} 已发送`; $('#batchInfo').textContent=`本批已选择 ${selected.size} 人（建议每批不超过 5 人）`; $('#contactList').innerHTML=rows.length?rows.map(c=>`<article class="card"><div class="card-main" data-action="copy-message" data-id="${c.id}" title="点击复制个性化消息"><label class="select-contact"><input type="checkbox" data-action="select" data-id="${c.id}" ${selected.has(c.id)?'checked':''}></label><div><h3>${esc(c.name)}</h3><p>${esc(c.company||'')} ${c.linkedin?`· <a href="${esc(c.linkedin)}" target="_blank" rel="noopener">LinkedIn</a>`:''}</p>${c.notes?`<p class="muted">${esc(c.notes)}</p>`:''}</div></div><div class="card-actions"><span class="status ${c.status}">${c.status==='sent'?'已发送':c.status==='skip'?'已跳过':'待联系'}</span><button class="secondary" data-action="message" data-id="${c.id}">准备消息</button><button class="secondary" data-action="status" data-id="${c.id}">${c.status==='skip'?'恢复待联系':'跳过'}</button><button class="secondary" data-action="edit" data-id="${c.id}">编辑</button><button class="danger" data-action="delete" data-id="${c.id}">删除</button></div></article>`).join(''):'<div class="empty">还没有联系人。可以导入 CSV 或新增联系人。</div>'}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function preview(){ $('#templatePreview').textContent=state.template.replaceAll('{GivenName}','Zixuan'); }
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`#${b.dataset.view}View`).classList.remove('hidden');if(b.dataset.view==='template'){ $('#templateText').value=state.template;preview();}});
$('#search').oninput=render; $('#statusFilter').onchange=render;
$('#selectFiveBtn').onclick=()=>{state.contacts.filter(c=>c.status==='pending').slice(0,5).forEach(c=>selected.add(c.id));render()};
$('#batchPrepareBtn').onclick=()=>{const queue=[...selected].map(id=>state.contacts.find(c=>c.id===id)).filter(Boolean).slice(0,5);if(!queue.length){alert('请先选择联系人');return}if(queue.length>5){alert('每批最多准备 5 位联系人');return}let i=0;const next=()=>{const c=queue[i];if(!c)return;const msg=state.template.replaceAll('{GivenName}',given(c.name));navigator.clipboard?.writeText(msg);if(c.linkedin)window.open(c.linkedin,'_blank','noopener');const done=confirm(`第 ${i+1}/${queue.length} 位：${c.name}\n消息已复制${c.linkedin?'，并打开 LinkedIn':''}。\n\n发送完成后点击“确定”继续下一位；取消则暂停。`);if(done){c.status='sent';c.sentAt=new Date().toISOString();selected.delete(c.id);save();render();i++;next()}};next()};
$('#clearSelectionBtn').onclick=()=>{selected.clear();render()};
$('#templateText').oninput=e=>{state.template=e.target.value;preview()}; $('#saveTemplate').onclick=()=>{save();alert('模板已保存')};
$('#copyTemplateBtn').onclick=()=>{navigator.clipboard?.writeText(state.template);alert('模板已复制')};
$('#addBtn').onclick=()=>openContact(); function openContact(c){$('#contactDialog').dataset.id=c?.id||'';$('#dialogTitle').textContent=c?'编辑联系人':'新增联系人';$('#nameInput').value=c?.name||'';$('#linkedinInput').value=c?.linkedin||'';$('#companyInput').value=c?.company||'';$('#contactDialog').showModal()}
$('#contactForm').onsubmit=e=>{e.preventDefault();const id=$('#contactDialog').dataset.id;let c=state.contacts.find(x=>x.id===id);if(c)Object.assign(c,{name:$('#nameInput').value,linkedin:$('#linkedinInput').value,company:$('#companyInput').value});else state.contacts.push({id:crypto.randomUUID(),name:$('#nameInput').value,linkedin:$('#linkedinInput').value,company:$('#companyInput').value,status:'pending'});save();$('#contactDialog').close();render()};
$('#contactList').onclick=e=>{const target=e.target;const id=target.dataset.id;if(target.dataset.action==='select'){target.checked?selected.add(id):selected.delete(id);render();return}if(target.dataset.action==='copy-message'){const c=state.contacts.find(x=>x.id===id);if(c){navigator.clipboard?.writeText(state.template.replaceAll('{GivenName}',given(c.name)));alert(`${c.name} 的个性化消息已复制`)}return}const b=target.closest('button');if(!b)return;const c=state.contacts.find(x=>x.id===b.dataset.id);if(!c)return;if(b.dataset.action==='edit')openContact(c);else if(b.dataset.action==='delete'){if(confirm(`确定删除 ${c.name} 吗？`)){state.contacts=state.contacts.filter(x=>x.id!==c.id);selected.delete(c.id);save();render()}}else if(b.dataset.action==='status'){c.status=c.status==='skip'?'pending':'skip';save();render()}else{if(c.status==='sent'&&!confirm('该联系人已标记为已发送，仍要再次准备消息吗？'))return;const msg=state.template.replaceAll('{GivenName}',given(c.name));navigator.clipboard?.writeText(msg);if(c.linkedin)window.open(c.linkedin,'_blank','noopener');if(confirm(`消息已复制${c.linkedin?'，并打开 LinkedIn':''}。\n\n发送完成后点击“确定”标记为已发送。`)){c.status='sent';c.sentAt=new Date().toISOString();selected.delete(c.id);save();render()}}};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const parse=l=>l.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/).map(x=>x.replace(/^"|"$/g,'').trim());const head=parse(lines.shift()).map(x=>x.toLowerCase());lines.forEach(line=>{const r=parse(line), name=r[head.findIndex(x=>/name|姓名/.test(x))]||r[0], linkedin=r[head.findIndex(x=>/linkedin/.test(x))]||'', company=r[head.findIndex(x=>/company|公司|学校/.test(x))]||'';if(name&&!state.contacts.some(c=>c.name===name&&c.linkedin===linkedin))state.contacts.push({id:crypto.randomUUID(),name,linkedin,company,status:'pending'})});save();render();e.target.value=''};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='master-linked-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#clearBtn').onclick=()=>{if(confirm('确定清空本机全部联系人和模板吗？')){state={contacts:[],template:defaultTemplate};save();render()}}; render();
const wordExcelInput=$('#wordExcelInput'),wordTemplateInput=$('#wordTemplateInput'),wordMergeBtn=$('#wordMergeBtn'),wordMergeStatus=$('#wordMergeStatus');
function refreshWordMerge(){const excel=wordExcelInput?.files[0],template=wordTemplateInput?.files[0];wordMergeBtn.disabled=!(excel&&template);wordMergeStatus.textContent=excel&&template?`已选择：${excel.name} + ${template.name}`:excel?`已选择 Excel：${excel.name}，还需选择 Word 模板。`:template?`已选择 Word 模板：${template.name}，还需选择 Excel。`:'尚未选择文件。'}
wordExcelInput?.addEventListener('change',refreshWordMerge);wordTemplateInput?.addEventListener('change',refreshWordMerge);wordMergeBtn?.addEventListener('click',()=>{const excel=wordExcelInput.files[0],template=wordTemplateInput.files[0];if(!excel||!template)return;alert(`文件已通过基础校验：\n${excel.name}\n${template.name}\n\n下一步请在 Word 中使用“邮件合并”选择该 Excel 作为收件人列表。桌面版本地桥接服务上线后，可直接打开 Word。`)});
let meetingRecorder=null,meetingChunks=[],meetingRecognition=null,meetingFinalTranscript='',meetingInterimTranscript='',meetingRecognitionRestarting=false;
$('#recordStartBtn')?.addEventListener('click',async()=>{if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){alert('当前浏览器不支持录音，请使用最新版 Chrome 并通过 HTTPS 打开网页。');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});meetingChunks=[];meetingFinalTranscript='';meetingInterimTranscript='';meetingRecorder=new MediaRecorder(stream);meetingRecorder.ondataavailable=e=>{if(e.data.size)meetingChunks.push(e.data)};meetingRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(meetingChunks,{type:meetingRecorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob),download=$('#downloadRecording');download.href=url;download.classList.remove('hidden');$('#recordStatus').textContent=meetingRecognition?'录音已结束；转写文字已保留，可下载完整录音。':'录音已结束；当前仅保存了录音，请检查浏览器转写支持。'};meetingRecorder.start(1000);const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(SR){meetingRecognition=new SR();meetingRecognition.lang='zh-CN';meetingRecognition.continuous=true;meetingRecognition.interimResults=true;meetingRecognition.maxAlternatives=1;meetingRecognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const text=e.results[i][0].transcript||'';if(e.results[i].isFinal)meetingFinalTranscript+=text+'\n';else interim+=text}meetingInterimTranscript=interim;const box=$('#meetingTranscript');if(box)box.value=meetingFinalTranscript+(interim?'\n'+interim:'');};meetingRecognition.onerror=e=>{if(e.error!=='no-speech'&&e.error!=='aborted')$('#recordStatus').textContent='正在录音；实时转写暂时中断，浏览器将自动重试（'+e.error+'）。'};meetingRecognition.onend=()=>{if(meetingRecorder?.state==='recording'&&!meetingRecognitionRestarting){meetingRecognitionRestarting=true;setTimeout(()=>{meetingRecognitionRestarting=false;try{meetingRecognition?.start()}catch(e){}},250)}};meetingRecognition.start();$('#recordStatus').textContent='正在录音并实时转写（浏览器模式）…'}else $('#recordStatus').textContent='正在录音；当前浏览器不支持自动转写，请稍后粘贴文字。';$('#recordStartBtn').disabled=true;$('#recordStopBtn').disabled=false}catch(err){const msg=err?.name==='NotAllowedError'?'麦克风权限被拒绝，请在浏览器和系统设置中允许麦克风。':err?.name==='NotFoundError'?'未找到可用麦克风。':'录音启动失败，请确认使用 HTTPS 和最新版 Chrome。';$('#recordStatus').textContent=msg;alert(msg)}});
$('#recordStopBtn')?.addEventListener('click',()=>{if(meetingRecorder?.state==='recording')meetingRecorder.stop();if(meetingRecognition){meetingRecognition.stop();meetingRecognition=null}$('#recordStartBtn').disabled=false;$('#recordStopBtn').disabled=true});
$('#summarizeMeetingBtn')?.addEventListener('click',()=>{const transcript=$('#meetingTranscript').value.trim(),template=$('#meetingTemplate').value;if(!transcript){alert('请先录音或粘贴会议文字');return}$('#meetingSummary').value=template.replace(/会议日期：/,'会议日期：'+new Date().toLocaleDateString('zh-CN'))+'\n\n会议原始记录：\n'+transcript});
$('#saveMeetingBtn')?.addEventListener('click',()=>{const summary=$('#meetingSummary').value.trim();if(!summary){alert('请先生成会议纪要');return}const list=JSON.parse(localStorage.getItem('master-linked-meetings')||'[]');list.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),summary});localStorage.setItem('master-linked-meetings',JSON.stringify(list));alert('会议纪要已保存到本机')});
const meetingView=$('#meeting-recordsView');if(meetingView&&!$('#meetingSetupStatus')){const setup=document.createElement('div');setup.className='panel meeting-setup';setup.innerHTML='<h2>本机浏览器检测</h2><div id="meetingCheckBox" class="meeting-checks" role="status">尚未检测</div><p id="meetingSetupStatus" class="muted">点击检测当前电脑和浏览器的能力。</p><button id="meetingSetupBtn" class="secondary">检测本机</button>';meetingView.insertBefore(setup,meetingView.querySelector('.meeting-panel'));$('#meetingSetupBtn').onclick=async()=>{const checks=[];const report=(name,ok,detail)=>{checks.push(`${ok?'✓':'✕'} ${name}：${detail}`);$('#meetingCheckBox').innerHTML=checks.map(x=>`<div>${x}</div>`).join('')};$('#meetingSetupStatus').textContent='正在检测，请稍候…';const secure=location.protocol==='https:'||location.hostname==='localhost';report('安全连接',secure,secure?'正常':'需要 HTTPS');const mic=!!navigator.mediaDevices?.getUserMedia;report('麦克风接口',mic,mic?'支持':'不支持');const rec=!!window.MediaRecorder;report('录音接口',rec,rec?'支持':'不支持');let format=false;if(rec&&MediaRecorder.isTypeSupported)format=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')||MediaRecorder.isTypeSupported('audio/mp4');report('录音格式',format,format?'支持':'浏览器格式受限');const speech=!!(window.SpeechRecognition||window.webkitSpeechRecognition);report('实时转写接口',speech,speech?'浏览器支持，效果因设备和环境而异':'浏览器不支持');let permission='未检测';if(mic){try{const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());permission='已允许';report('麦克风权限',true,permission)}catch(e){permission=e?.name==='NotAllowedError'?'被拒绝':'不可用';report('麦克风权限',false,permission)}}const ready=secure&&mic&&rec&&format&&permission==='已允许';$('#meetingSetupStatus').textContent=ready?'检测完成：本机可以录音；实时转写为浏览器能力。':'检测完成：本机录音条件不完整，请按上方 ✕ 提示处理。'}};
const waveCanvas=document.createElement('canvas');waveCanvas.id='meetingWaveform';waveCanvas.width=760;waveCanvas.height=90;waveCanvas.className='meeting-waveform';const transcriptBox=$('#meetingTranscript');transcriptBox?.parentNode.insertBefore(waveCanvas,transcriptBox);let visualStream=null,visualCtx=null,visualAnalyser=null,visualFrame=0;$('#recordStartBtn')?.addEventListener('click',async()=>{try{visualStream=await navigator.mediaDevices.getUserMedia({audio:true});visualCtx=new (window.AudioContext||window.webkitAudioContext)();visualAnalyser=visualCtx.createAnalyser();visualAnalyser.fftSize=512;visualCtx.createMediaStreamSource(visualStream).connect(visualAnalyser);const c=waveCanvas.getContext('2d'),data=new Uint8Array(visualAnalyser.fftSize);const draw=()=>{visualAnalyser.getByteTimeDomainData(data);c.clearRect(0,0,waveCanvas.width,waveCanvas.height);c.strokeStyle='#0a66c2';c.lineWidth=3;c.beginPath();data.forEach((v,i)=>{const x=i/(data.length-1)*waveCanvas.width,y=waveCanvas.height/2+(v-128)*.32;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();visualFrame=requestAnimationFrame(draw)};draw()}catch(e){}});$('#recordStopBtn')?.addEventListener('click',()=>{if(visualFrame)cancelAnimationFrame(visualFrame);visualStream?.getTracks().forEach(t=>t.stop());visualCtx?.close();visualStream=null;visualCtx=null;visualAnalyser=null;const c=waveCanvas.getContext('2d');c.clearRect(0,0,waveCanvas.width,waveCanvas.height)});
const meetingActionStatus=document.createElement('p');meetingActionStatus.id='meetingActionStatus';meetingActionStatus.className='muted';meetingActionStatus.textContent='等待操作。请先录音或粘贴会议文字。';const summaryBtn=$('#summarizeMeetingBtn'),saveBtn=$('#saveMeetingBtn');if(summaryBtn){summaryBtn.parentElement.insertBefore(meetingActionStatus,summaryBtn.parentElement.firstChild);summaryBtn.addEventListener('click',()=>{setTimeout(()=>{if($('#meetingSummary').value.trim()){meetingActionStatus.textContent='✓ 会议纪要已生成，请在下方检查并修改。';$('#meetingSummary').scrollIntoView({behavior:'smooth',block:'center'})}else meetingActionStatus.textContent='未生成：请先录音或粘贴会议文字。'},50)})}saveBtn?.addEventListener('click',()=>{setTimeout(()=>{meetingActionStatus.textContent='✓ 会议纪要已保存到本机。'},50)});
let meetingRestartTimer=null;$('#recordStartBtn')?.addEventListener('click',()=>{clearInterval(meetingRestartTimer);meetingRestartTimer=setInterval(()=>{if(meetingRecorder?.state==='recording'&&meetingRecognition){try{meetingRecognition.start()}catch(e){}}},5000)});$('#recordStopBtn')?.addEventListener('click',()=>{clearInterval(meetingRestartTimer);meetingRestartTimer=null});
$('#meetingSetupBtn')?.addEventListener('click',()=>{const p=$('#meetingSetupStatus');let n=0;const timer=setInterval(()=>{if(!p||p.textContent.startsWith('检测完成')){clearInterval(timer);if(p)p.className=p.textContent.includes('可以录音')?'meeting-status success':'meeting-status error'}if(++n>30)clearInterval(timer)},200)});

// 兼容 LinkedIn 原生 Connections.csv：First Name、Last Name、URL、Company、Position。
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const parse=l=>l.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.replace(/^\"|\"$/g,'').trim());const head=parse(lines.shift()).map(x=>x.toLowerCase());const idx=ps=>head.findIndex(x=>ps.some(p=>p.test(x)));let added=0;for(const line of lines){const r=parse(line),first=r[idx([/first name/,/^first$/,/名/])]||'',last=r[idx([/last name/,/^last$/,/姓/])]||'',name=first&&last?`${first} ${last}`:(r[idx([/^name$/, /姓名/])]||first||r[0]),linkedin=r[idx([/linkedin/,/^url$/, /profile url/,/个人主页/])]||'',company=r[idx([/company/,/公司/,/学校/])]||'',position=r[idx([/position/,/title/,/职位/])]||'';if(name&&!state.contacts.some(c=>c.name===name&&c.linkedin===linkedin)){state.contacts.push({id:crypto.randomUUID(),name,linkedin,company,position,status:'pending'});added++}}save();render();e.target.value='';alert(`导入完成：新增 ${added} 位联系人。`)};

function renderMap(){const q=($('#mapSearch')?.value||'').toLowerCase();const contacts=state.contacts;const groups={};contacts.forEach(c=>{const key=c.company||'未填写公司 / 学校';groups[key]=(groups[key]||0)+1});const sorted=Object.entries(groups).sort((a,b)=>b[1]-a[1]);const max=sorted[0]?.[1]||1;$('#mapTotal').textContent=contacts.length;$('#mapCompanies').textContent=Object.keys(groups).length;$('#mapSent').textContent=contacts.filter(c=>c.status==='sent').length;$('#companyMap').innerHTML=sorted.length?sorted.slice(0,12).map(([name,n])=>`<div class="company-row"><span>${esc(name)}</span><span class="company-bar"><i style="width:${Math.round(n/max*100)}%"></i></span><b>${n}</b></div>`).join(''):'<div class="muted">导入 Connections.csv 后，这里会自动生成分布。</div>';const people=contacts.filter(c=>[c.name,c.company,c.position,c.status].join(' ').toLowerCase().includes(q)).slice(0,100);$('#mapPeople').innerHTML=people.length?people.map(c=>`<div class="map-person"><div><strong>${esc(c.name)}</strong><br><small>${esc(c.position||'未填写职位')} · ${esc(c.company||'未填写公司 / 学校')}</small></div><span class="status ${c.status}">${c.status==='sent'?'已发送':c.status==='skip'?'已跳过':'待联系'}</span></div>`).join(''):'<div class="muted">暂无匹配联系人。</div>'}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`#${b.dataset.view}View`).classList.remove('hidden');if(b.dataset.view==='template'){$('#templateText').value=state.template;preview()}if(b.dataset.view==='connections-map')renderMap()});
$('#mapSearch').oninput=renderMap;
const _renderMap=renderMap;renderMap=function(){_renderMap();const people=document.querySelectorAll('.map-person');people.forEach(el=>el.onclick=()=>{const name=el.querySelector('strong')?.textContent;const c=state.contacts.find(x=>x.name===name);if(!c)return;$('#personDetail').innerHTML=`<strong>${esc(c.name)}</strong><br>公司 / 学校：${esc(c.company||'待补充')}<br>职位：${esc(c.position||'待补充')}<br>连接日期：${esc(c.connectedOn||'待补充')}<br>工作年限：${esc(c.workYears||'待补充')}<br>工作状态：${esc(c.workStatus||'未知')}<br>技术方向：${esc(c.focus||'待补充')}<br>${c.linkedin?`<a href="${esc(c.linkedin)}" target="_blank" rel="noopener">打开 LinkedIn 主页</a>`:''}`})};
function openContact(c){$('#contactDialog').dataset.id=c?.id||'';$('#dialogTitle').textContent=c?'编辑联系人':'新增联系人';$('#nameInput').value=c?.name||'';$('#linkedinInput').value=c?.linkedin||'';$('#companyInput').value=c?.company||'';$('#positionInput').value=c?.position||'';$('#workYearsInput').value=c?.workYears||'';$('#workStatusInput').value=c?.workStatus||'';$('#focusInput').value=c?.focus||'';$('#contactDialog').showModal()}
$('#contactForm').onsubmit=e=>{e.preventDefault();const id=$('#contactDialog').dataset.id;let c=state.contacts.find(x=>x.id===id);const fields={name:$('#nameInput').value.trim(),linkedin:$('#linkedinInput').value.trim(),company:$('#companyInput').value.trim(),position:$('#positionInput').value.trim(),workYears:$('#workYearsInput').value.trim(),workStatus:$('#workStatusInput').value.trim(),focus:$('#focusInput').value.trim()};if(c)Object.assign(c,fields);else state.contacts.push({id:crypto.randomUUID(),...fields,status:'pending'});save();$('#contactDialog').close();render()};
// LinkedIn Connections.csv 的“Connected On”字段用于建立联系人时间线。
const importConnections=$('#importInput').onchange;
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const parse=l=>l.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.replace(/^\"|\"$/g,'').trim());const head=parse(lines.shift()).map(x=>x.toLowerCase());const idx=ps=>head.findIndex(x=>ps.some(p=>p.test(x)));let added=0;for(const line of lines){const r=parse(line),first=r[idx([/first name/,/^first$/,/名/])]||'',last=r[idx([/last name/,/^last$/,/姓/])]||'',name=first&&last?`${first} ${last}`:(r[idx([/^name$/, /姓名/])]||first||r[0]),linkedin=r[idx([/linkedin/,/^url$/, /profile url/,/个人主页/])]||'',company=r[idx([/company/,/公司/,/学校/])]||'',position=r[idx([/position/,/title/,/职位/])]||'',connectedOn=r[idx([/connected on/,/connection date/,/连接日期/])]||'';if(name&&!state.contacts.some(c=>c.name===name&&c.linkedin===linkedin)){state.contacts.push({id:crypto.randomUUID(),name,linkedin,company,position,connectedOn,workYears:'',workStatus:'',focus:'',status:'pending'});added++}}save();render();e.target.value='';alert(`导入完成：新增 ${added} 位联系人。`)};

// Intercept LinkedIn exports that contain the explanatory Notes preamble before the header.
$('#importInput').addEventListener('change',async e=>{e.stopImmediatePropagation();const file=e.target.files[0];if(!file)return;const raw=(await file.text()).split(/\r?\n/);const headerAt=raw.findIndex(line=>/First Name/i.test(line)&&/Last Name/i.test(line)&&/Company/i.test(line));if(headerAt<0){alert('未找到 Connections.csv 表头');return}const lines=raw.slice(headerAt+1).filter(Boolean);const parse=l=>l.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.replace(/^\"|\"$/g,'').trim());const head=parse(raw[headerAt]).map(x=>x.toLowerCase());const idx=ps=>head.findIndex(x=>ps.some(p=>p.test(x)));let added=0;for(const line of lines){const r=parse(line),first=r[idx([/first name/,/^first$/,/名/])]||'',last=r[idx([/last name/,/^last$/,/姓/])]||'',name=first&&last?`${first} ${last}`:(r[idx([/^name$/, /姓名/])]||first||'').trim(),linkedin=r[idx([/linkedin/,/^url$/, /profile url/,/个人主页/])]||'',company=r[idx([/company/,/公司/,/学校/])]||'',position=r[idx([/position/,/title/,/职位/])]||'',connectedOn=r[idx([/connected on/,/connection date/,/连接日期/])]||'';if(name&&!state.contacts.some(c=>c.name===name&&c.linkedin===linkedin)){state.contacts.push({id:crypto.randomUUID(),name,linkedin,company,position,connectedOn,workYears:'',workStatus:'',focus:'',status:'pending'});added++}}save();render();e.target.value='';alert(`导入完成：新增 ${added} 位联系人。`)},true);
