const KEY='master-linked-state-v1';
const defaultTemplate=`{GivenName}，您好啊！\n\n我是华为加拿大研究所的 Daniel Jiang。我们近期正在提前了解 NeurIPS 2026 的参会情况，希望更好地参与会议并与相关领域的研究人员保持联系。\n\n因此冒昧请问一下：您今年是否计划参加 NeurIPS 2026？如果参加，预计会去哪个会场？\n\n感谢您的时间，祝好！\n\nDaniel`;
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{contacts:[],template:defaultTemplate};
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
function given(name){return (name||'').trim().split(/\s+/)[0].replace(/[（(].*$/,'')}
function render(){const q=($('#search').value||'').toLowerCase(), f=$('#statusFilter').value; const rows=state.contacts.filter(c=>(f==='all'||c.status===f)&&[c.name,c.company,c.status].join(' ').toLowerCase().includes(q)); $('#stats').textContent=`${state.contacts.length} 位联系人 · ${state.contacts.filter(c=>c.status==='sent').length} 已发送`; $('#contactList').innerHTML=rows.length?rows.map(c=>`<article class="card"><div class="card-main"><h3>${esc(c.name)}</h3><p>${esc(c.company||'')} ${c.linkedin?`· <a href="${esc(c.linkedin)}" target="_blank" rel="noopener">LinkedIn</a>`:''}</p></div><div class="card-actions"><span class="status ${c.status}">${c.status==='sent'?'已发送':c.status==='skip'?'已跳过':'待联系'}</span><button class="secondary" data-action="message" data-id="${c.id}">准备消息</button><button class="secondary" data-action="edit" data-id="${c.id}">编辑</button></div></article>`).join(''):'<div class="empty">还没有联系人。可以导入 CSV 或新增联系人。</div>'}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function preview(){ $('#templatePreview').textContent=state.template.replaceAll('{GivenName}','Zixuan'); }
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`#${b.dataset.view}View`).classList.remove('hidden');if(b.dataset.view==='template'){ $('#templateText').value=state.template;preview();}});
$('#search').oninput=render; $('#statusFilter').onchange=render;
$('#templateText').oninput=e=>{state.template=e.target.value;preview()}; $('#saveTemplate').onclick=()=>{save();alert('模板已保存')};
$('#addBtn').onclick=()=>openContact(); function openContact(c){$('#contactDialog').dataset.id=c?.id||'';$('#dialogTitle').textContent=c?'编辑联系人':'新增联系人';$('#nameInput').value=c?.name||'';$('#linkedinInput').value=c?.linkedin||'';$('#companyInput').value=c?.company||'';$('#contactDialog').showModal()}
$('#contactForm').onsubmit=e=>{e.preventDefault();const id=$('#contactDialog').dataset.id;let c=state.contacts.find(x=>x.id===id);if(c)Object.assign(c,{name:$('#nameInput').value,linkedin:$('#linkedinInput').value,company:$('#companyInput').value});else state.contacts.push({id:crypto.randomUUID(),name:$('#nameInput').value,linkedin:$('#linkedinInput').value,company:$('#companyInput').value,status:'pending'});save();$('#contactDialog').close();render()};
$('#contactList').onclick=e=>{const b=e.target.closest('button');if(!b)return;const c=state.contacts.find(x=>x.id===b.dataset.id);if(b.dataset.action==='edit')openContact(c);else{const msg=state.template.replaceAll('{GivenName}',given(c.name));navigator.clipboard?.writeText(msg);if(c.linkedin)window.open(c.linkedin,'_blank','noopener');if(confirm(`消息已复制${c.linkedin?'，并打开 LinkedIn':''}。\n\n发送完成后点击“确定”标记为已发送。`)){c.status='sent';c.sentAt=new Date().toISOString();save();render()}}};
$('#importInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);const parse=l=>l.split(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/).map(x=>x.replace(/^"|"$/g,'').trim());const head=parse(lines.shift()).map(x=>x.toLowerCase());lines.forEach(line=>{const r=parse(line), name=r[head.findIndex(x=>/name|姓名/.test(x))]||r[0], linkedin=r[head.findIndex(x=>/linkedin/.test(x))]||'', company=r[head.findIndex(x=>/company|公司|学校/.test(x))]||'';if(name&&!state.contacts.some(c=>c.name===name&&c.linkedin===linkedin))state.contacts.push({id:crypto.randomUUID(),name,linkedin,company,status:'pending'})});save();render();e.target.value=''};
$('#exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='master-linked-backup.json';a.click();URL.revokeObjectURL(a.href)};
$('#clearBtn').onclick=()=>{if(confirm('确定清空本机全部联系人和模板吗？')){state={contacts:[],template:defaultTemplate};save();render()}}; render();
